---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: coney
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - name: Download latest x86_64 RPM
  run: |
    gh release download --repo xarbit/plasma6-applet-appgrid \
      --pattern '*x86_64*.rpm' \
      --output plasma6-applet-appgrid.rpm
  env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  - type: dnf
    repos:
      copr:
        - deltacopy/darkly
        - infinality/kwin-effects-better-blur-dx
    install:
      packages:
        - darkly
        - kwin-effects-better-blur-dx
        - plasma6-applet-appgrid
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
